"""Build glossary/speeches.yaml from Notion (or from a CSV export of it).

NEVER RUNS DURING THE WEDDING. This is an authoring tool: it writes a local file
that captions.py reads at startup. The live system has no Notion dependency, no
token and no network call to anything but Azure. Run it whenever the speeches
change, then restart captions.py.

  uv run python scripts/import_speeches.py --csv ~/Downloads/Speeches.csv
  uv run python scripts/import_speeches.py --notion <data_source_id>

The Notion table needs these columns (names are case-insensitive):

  Speaker | Lang | Said | ES | EN | TR

  Lang    es, en or tr — the language the line is SPOKEN in
  Said    the sentence as it will actually be said, in that language
  ES/EN/TR  the three translations. The one matching Lang can repeat Said.

ONE SENTENCE PER ROW. Matching is per-sentence, so a row holding a whole
paragraph will never match anything.
"""
import argparse
import csv
import json
import os
import re
import sys
import urllib.error
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from dotenv import load_dotenv  # noqa: E402

load_dotenv()
NOTION_TOKEN = os.getenv("NOTION_TOKEN", "")
NOTION_VERSION = os.getenv("NOTION_VERSION", "2025-09-03")
OUT = "glossary/speeches.yaml"
WANTED = ("speaker", "lang", "said", "es", "en", "tr")

HEADER = '''# Pre-translated lines from the prepared speeches, vows and ceremony order.
#
# GENERATED by scripts/import_speeches.py — edit in Notion, not here, or your
# next import will overwrite it.
#
# When a finished sentence closely matches `said`, the screen shows these human
# translations instead of the machine's. Anything unmatched falls through to
# live translation, so a speaker going off-script loses nothing.

'''


def notion_rows(source_id: str) -> list[dict]:
    """Query a Notion data source. The 2025-09-03 API split databases into data
    sources, so we try that first and fall back to the older database endpoint."""
    if not NOTION_TOKEN:
        sys.exit("NOTION_TOKEN missing from .env — see the Notion setup notes")

    def post(url: str) -> dict:
        req = urllib.request.Request(
            url, data=b"{}", method="POST",
            headers={"Authorization": f"Bearer {NOTION_TOKEN}",
                     "Notion-Version": NOTION_VERSION,
                     "Content-Type": "application/json"})
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.loads(r.read())

    for url in (f"https://api.notion.com/v1/data_sources/{source_id}/query",
                f"https://api.notion.com/v1/databases/{source_id}/query"):
        try:
            payload = post(url)
        except urllib.error.HTTPError as e:
            detail = e.read().decode()[:300]
            print(f"  {url.split('/v1/')[1].split('/')[0]}: HTTP {e.code} {detail}")
            continue
        return [flatten(p) for p in payload.get("results", [])]
    sys.exit("Notion query failed on both endpoints — see the errors above.\n"
             "Check the integration is shared with the page, and that you used a\n"
             "DATA SOURCE id (not a database id) for the 2025-09-03 API.")


def flatten(page: dict) -> dict:
    """Notion property values -> plain strings."""
    out = {}
    for name, prop in (page.get("properties") or {}).items():
        kind = prop.get("type")
        if kind in ("title", "rich_text"):
            out[name.lower()] = "".join(t.get("plain_text", "") for t in prop[kind])
        elif kind == "select":
            out[name.lower()] = (prop["select"] or {}).get("name", "")
        elif kind == "number":
            out[name.lower()] = prop["number"]
    return out


def csv_rows(path: str) -> list[dict]:
    with open(path, encoding="utf-8-sig") as fh:
        return [{k.strip().lower(): (v or "").strip() for k, v in row.items() if k}
                for row in csv.DictReader(fh)]


def yaml_escape(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", nargs="+", help="one or more CSV exports")
    ap.add_argument("--notion", help="Notion data source id (or database id)")
    ap.add_argument("--out", default=OUT)
    args = ap.parse_args()
    if not args.csv and not args.notion:
        ap.error("give --csv or --notion")

    if args.csv:
        rows = []
        for path in args.csv:          # one CSV per speaker, combined here
            got = csv_rows(path)
            print(f"  {os.path.basename(path)}: {len(got)} rows")
            rows += got
    else:
        rows = notion_rows(args.notion)
    print(f"read {len(rows)} rows")

    good, problems = [], []
    for i, r in enumerate(rows, 1):
        who = (r.get("speaker") or "").strip()
        lang = (r.get("lang") or "").strip().lower()[:2]
        said = (r.get("said") or "").strip()
        if not said:
            continue                                   # blank row, ignore quietly
        if lang not in ("es", "en", "tr"):
            problems.append(f"row {i}: lang {r.get('lang')!r} is not es/en/tr — skipped")
            continue
        tr = {k: (r.get(k) or "").strip() for k in ("es", "en", "tr")}
        tr[lang] = tr[lang] or said                    # own language defaults to Said
        missing = [k for k, v in tr.items() if not v]
        if missing:
            problems.append(f"row {i} ({who or lang}): missing {'/'.join(missing)} — skipped")
            continue
        # Matching is per sentence; a paragraph will never match.
        if len(re.findall(r"[.!?…]\s+\S", said)) >= 1:
            problems.append(f"row {i} ({who or lang}): looks like more than one "
                            f"sentence, split it — kept anyway")
        good.append({"who": who, "lang": lang, "said": said, **tr})

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(HEADER)
        fh.write("lines:\n")
        for e in good:
            if e["who"]:
                fh.write(f"  # {e['who']}\n")
            fh.write(f"  - lang: {e['lang']}\n")
            for k in ("said", "es", "en", "tr"):
                fh.write(f"    {k}: {yaml_escape(e[k])}\n")
            fh.write("\n")

    print(f"wrote {len(good)} lines to {args.out}")
    if problems:
        print(f"\n{len(problems)} thing(s) to look at:")
        for p in problems:
            print(f"  - {p}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
